version: "3.7"
secrets:
  google_credentials:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}
services:
  web:
    image: purity-vision:latest
    depends_on:
      - postgres
    links:
      - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; ./purity-vision -port 8080'
    ports:
      - "8080:8080"
    secrets:
      - google_credentials
    environment:
      - PURITY_DB_HOST=${PURITY_DB_HOST}
      - PURITY_DB_PORT=${PURITY_DB_PORT}
      - PURITY_DB_NAME=${PURITY_DB_NAME}
      - PURITY_DB_USER=${PURITY_DB_USER}
      - PURITY_DB_PASS=${PURITY_DB_PASS}
      - PURITY_DB_SSL_MODE=${PURITY_DB_SSL_MODE}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_credentials
      - PROJECT_ROOT=${PROJECT_ROOT}
      - PURITY_LOG_LEVEL=${PURITY_LOG_LEVEL}
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - PROJECT_ROOT=${PROJECT_ROOT}
      - POSTGRES_DB=${PURITY_DB_NAME}
      - POSTGRES_PASSWORD=${PURITY_DB_PASS}
    volumes:
      # - "/pg-docker-data:/var/lib/postgresql/data"
      - "/Users/gb/Desktop/pg-data:/var/lib/postgresql/data"
      - "${PROJECT_ROOT}/build:/docker-entrypoint-initdb.d"
